'use strict';
(()=>{
const $=id=>document.getElementById(id),canvas=$('world'),panel=$('panel');
const KEY='tara-ryvok-v1',fresh=()=>({v:1,wallet:0,best:0,total:0,runs:0,skin:0,owned:[0],magnet:0,shield:0,bonus:0,sound:true,claims:[]});
function validate(s){const d=fresh();if(!s||s.v!==1)throw Error('Неверный формат');for(const k of ['wallet','best','total','runs'])d[k]=Math.min(1e9,Math.max(0,Math.floor(Number(s[k])||0)));for(const k of ['magnet','shield','bonus'])d[k]=Math.min(3,Math.max(0,Math.floor(Number(s[k])||0)));d.owned=[0,...[1,2,3].filter(i=>Array.isArray(s.owned)&&s.owned.includes(i))];d.skin=d.owned.includes(s.skin)?s.skin:0;d.sound=s.sound!==false;d.claims=Array.isArray(s.claims)?s.claims.filter(n=>Number.isInteger(n)&&n>=0&&n<3):[];return d}
let save=fresh(),storageOK=true;try{const raw=localStorage.getItem(KEY);if(raw)save=validate(JSON.parse(raw));}catch(e){storageOK=false}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(save))}catch(e){storageOK=false;toast('Нет доступа к сохранению. Сделайте экспорт.')}}
let toastTimer;function toast(t){$('toast').textContent=t;$('toast').style.opacity=1;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.opacity=0,2200)}
// Original batched WebGL renderer with smooth mesh lighting and articulated models.
const gl=canvas.getContext('webgl',{alpha:false,antialias:true,stencil:true,powerPreference:'high-performance'});
if(!gl){panel.innerHTML='<div class="sheet"><h2>Нужен WebGL</h2><p>Откройте игру в браузере с поддержкой аппаратной 3D-графики.</p></div>';return}
// Environment renderer: per-vertex normals, packed colour, material id. One directional sun plus hemisphere ambient shared with the
// character shader, per-material procedural detail anchored to absolute world position, planar shadow pass onto the road.
const vs=`attribute vec3 a;attribute vec3 n;attribute float c;attribute float m;uniform float aspect;uniform mediump float shadowPass;varying vec3 vC;varying vec3 vN;varying vec3 vW;varying float vM;varying float vFog;
void main(){vec3 p=a;if(shadowPass>.5){vec3 L=normalize(vec3(-.42,.78,-.50));p=a-L*((a.y-.045)/L.y);}vW=p;vN=n;vM=m;float r=floor(c/65536.),g=floor((c-r*65536.)/256.),b=c-r*65536.-g*256.;vC=vec3(r,g,b)/255.;
vec3 v=p-vec3(0.,5.2,-8.);float y=v.y*.951+v.z*.309;float z=-v.y*.309+v.z*.951;gl_Position=vec4(v.x*1.64/aspect,y*1.64,z*1.002-.2002,z);vFog=clamp((z-30.)/70.,0.,1.);}`;
const fs=`
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif
varying vec3 vC;varying vec3 vN;varying vec3 vW;varying float vM;varying float vFog;uniform float scroll;uniform mediump float shadowPass;
float hash(vec2 q){return fract(sin(dot(q,vec2(12.9898,78.233)))*43758.5453);}
float hash3(vec3 q){return fract(sin(dot(q,vec3(12.9898,78.233,37.719)))*43758.5453);}
void main(){
 if(shadowPass>.5){gl_FragColor=vec4(.02,.04,.07,.44);return;}
 vec3 n=normalize(vN),L=normalize(vec3(-.42,.78,-.50)),eye=normalize(vec3(0.,5.2,-8.)-vW),P=vec3(vW.x,vW.y,vW.z+scroll),col=vC;float m=vM;
 if(m>10.5&&m<11.5){gl_FragColor=vec4(col,1.);return;}
 float specAmt=0.,specPow=16.,wrap=0.;
 if(m<.5){col*=.96+.07*hash3(floor(P*40.));}
 else if(m<1.5){float g=hash(floor(P.xz*60.)),g2=hash(floor(P.xz*7.)+3.);col*=.84+.24*g+.10*g2;float wear=exp(-pow((abs(P.x)-1.55)/.30,2.))+exp(-pow(abs(P.x)/.30,2.))*.6;col*=1.-.07*wear;col*=1.-.08*step(.93,hash(floor(P.xz*vec2(.5,.15))));}
 else if(m<2.5){float seam=max(step(fract(P.z/3.25),.02),step(fract(P.y/2.8),.025));col*=1.-.30*seam;col*=.94+.10*hash(floor(P.xz*3.)+floor(P.y*1.5));col*=1.-.20*exp(-P.y*.6);col*=1.-.06*hash(floor(P.xz*9.))*smoothstep(3.,0.,P.y);}
 else if(m<3.5){vec3 R=reflect(-eye,n);col=mix(col,vec3(.62,.74,.86),.30+.35*clamp(R.y,0.,1.));specAmt=.9;specPow=60.;}
 else if(m<4.5){col*=.78+.38*hash3(floor(P*6.));wrap=.45;}
 else if(m<5.5){col*=.88+.18*hash(floor(vec2(P.z*35.,P.y*4.+P.x*4.)));col*=1.+.05*sin(P.y*60.+P.z*3.);specAmt=.06;specPow=10.;}
 else if(m<6.5){specAmt=.45;specPow=28.;col*=.98+.04*hash3(floor(P*30.));}
 else if(m<7.5){float j=max(step(fract(P.z/1.0),.03),step(fract(P.x/1.1),.03));col*=1.-.22*j;col*=.90+.16*hash(floor(P.xz*12.));}
 else if(m<8.5){col*=.82+.36*hash(floor(P.xz*22.));col=mix(col,vec3(.42,.36,.24),.4*step(.6,hash(floor(P.xz*1.3))));}
 else if(m<9.5){specAmt=.10;specPow=12.;col*=.95+.08*hash3(floor(P*40.));}
 else if(m<10.5){float row=floor(P.y/.085);float u=P.z/.24+mod(row,2.)*.5;float mortar=max(step(fract(P.y/.085),.14),step(fract(u),.10));col*=.85+.30*hash(vec2(floor(u),row));col=mix(col,vec3(.72,.68,.62),mortar*.8);}
 else if(m>12.5){vec3 R=reflect(-eye,n);col=mix(col,vec3(.62,.74,.86),.08+.10*clamp(R.y,0.,1.));specAmt=1.1;specPow=70.;wrap=.25;}
 else if(m>11.5){gl_FragColor=vec4(mix(col*1.15,vec3(.68,.79,.87),vFog*.6),1.);return;}
 float ndl=dot(n,L),diff=max(0.,mix(ndl,ndl*.5+.5,wrap));
 vec3 amb=mix(vec3(.36,.32,.28),vec3(.62,.74,.86),n.y*.5+.5)*.95;
 vec3 color=col*(amb+vec3(1.08,1.0,.90)*diff*1.12);
 vec3 h=normalize(L+eye);color+=vec3(1.,.96,.88)*pow(max(0.,dot(n,h)),specPow)*specAmt;
 color+=vec3(.55,.68,.80)*pow(1.-max(0.,dot(n,eye)),4.)*.10*specAmt;
 color=color*1.06/(1.+color*.08);
 gl_FragColor=vec4(mix(color,vec3(.68,.79,.87),vFog),1.);}`;
function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vs));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('WebGL link');gl.useProgram(program);const buffer=gl.createBuffer();const ENV_STRIDE=32,envAttribs=[['a',3,0],['n',3,12],['c',1,24],['m',1,28]].map(([name,size,offset])=>({loc:gl.getAttribLocation(program,name),size,offset}));function bindEnv(){gl.useProgram(program);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);for(const at of envAttribs){gl.enableVertexAttribArray(at.loc);gl.vertexAttribPointer(at.loc,at.size,gl.FLOAT,false,ENV_STRIDE,at.offset);}}bindEnv();const aspect=gl.getUniformLocation(program,'aspect'),uScroll=gl.getUniformLocation(program,'scroll'),uShadow=gl.getUniformLocation(program,'shadowPass');gl.enable(gl.DEPTH_TEST);
// Translucent iridescent energy dome for the shield: a separate blended pass with its own shader.
const domeProgram=gl.createProgram();gl.attachShader(domeProgram,shader(gl.VERTEX_SHADER,`attribute vec3 a;uniform vec3 center;uniform vec3 radii;uniform float aspect;varying vec3 vn;varying vec3 vw;void main(){vw=center+a*radii;vn=normalize(a/radii);vec3 p=vw-vec3(0.,5.2,-8.);float y=p.y*.951+p.z*.309;float z=-p.y*.309+p.z*.951;gl_Position=vec4(p.x*1.64/aspect,y*1.64,z*1.002-.2002,z);}`));
gl.attachShader(domeProgram,shader(gl.FRAGMENT_SHADER,`precision mediump float;varying vec3 vn;varying vec3 vw;uniform float time;
void main(){vec3 n=normalize(vn),eye=normalize(vec3(0.,5.2,-8.)-vw);float facing=abs(dot(n,eye)),rim=pow(1.-facing,2.4);
 float h=facing*3.2+time*1.5+n.y*2.4;vec3 iri=vec3(.5+.5*sin(h),.5+.5*sin(h+2.09),.5+.5*sin(h+4.19));vec3 base=mix(vec3(.40,.82,1.0),iri,.6);
 vec2 uv=vec2(atan(n.x,n.z)*1.9,n.y*3.2-time*.55);float cell=max(abs(fract(uv.x)-.5),abs(fract(uv.y)-.5));float lines=smoothstep(.40,.48,cell)*.45;
 float band=smoothstep(.06,.0,abs(fract(n.y*1.4-time*.7)-.5))*.6;
 float alpha=.09+.55*rim+lines*.35+band*.18;gl_FragColor=vec4(base*(.7+rim*1.1+lines*.8+band*.6),alpha);}`));
gl.linkProgram(domeProgram);if(!gl.getProgramParameter(domeProgram,gl.LINK_STATUS))throw Error('WebGL dome link');
const domeLoc=gl.getAttribLocation(domeProgram,'a'),domeU=Object.fromEntries(['center','radii','aspect','time'].map(k=>[k,gl.getUniformLocation(domeProgram,k)]));
const domeMesh=(()=>{const pts=[],segs=22,rings=12,pt=(i,j)=>{const a=i/rings*Math.PI,b=j/segs*Math.PI*2;return [Math.sin(a)*Math.cos(b),Math.cos(a),Math.sin(a)*Math.sin(b)];};for(let i=0;i<rings;i++)for(let j=0;j<segs;j++){const q=[pt(i,j),pt(i+1,j),pt(i+1,j+1),pt(i,j+1)];for(const k of [0,1,2,0,2,3])pts.push(...q[k]);}return new Float32Array(pts);})();
const domeBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,domeBuffer);gl.bufferData(gl.ARRAY_BUFFER,domeMesh,gl.STATIC_DRAW);
function dome(cx,cy,cz,rx,ry,rz,aspectValue){gl.useProgram(domeProgram);gl.bindBuffer(gl.ARRAY_BUFFER,domeBuffer);gl.enableVertexAttribArray(domeLoc);gl.vertexAttribPointer(domeLoc,3,gl.FLOAT,false,12,0);gl.uniform3f(domeU.center,cx,cy,cz);gl.uniform3f(domeU.radii,rx,ry,rz);gl.uniform1f(domeU.aspect,aspectValue);gl.uniform1f(domeU.time,time);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);gl.drawArrays(gl.TRIANGLES,0,domeMesh.length/3);gl.depthMask(true);gl.disable(gl.BLEND);gl.disableVertexAttribArray(domeLoc);}
const colors={road:[.20,.28,.31],walk:[.54,.58,.54],green:[.28,.54,.35],dark:[.10,.17,.22],wood:[.51,.28,.15],skin:[.81,.58,.39],glass:[.26,.65,.72],lime:[.76,.93,.29]};
let vertices=new Float32Array(3600000),vi=0;const faces=[[0,1,2,0,2,3,0,0,-1],[4,7,6,4,6,5,0,0,1],[0,4,5,0,5,1,0,-1,0],[3,2,6,3,6,7,0,1,0],[1,5,6,1,6,2,1,0,0],[0,3,7,0,7,4,-1,0,0]];// Material ids for the environment shader: 0 matte, 1 asphalt, 2 concrete panel, 3 glass, 4 foliage, 5 wood, 6 paint/metal, 7 pavement, 8 verge, 9 rubber, 10 brick, 11 sky, 12 emissive, 13 coloured glass.
let mat=0;const pack=c=>(Math.max(0,Math.min(255,c[0]*255))|0)*65536+(Math.max(0,Math.min(255,c[1]*255))|0)*256+(Math.max(0,Math.min(255,c[2]*255))|0);
function box(x,y,z,w,h,d,col,rot=0){const cs=Math.cos(rot),sn=Math.sin(rot),pts=[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]].map(p=>{const a=p[0]*w/2,b=p[2]*d/2;return[x+a*cs+b*sn,y+p[1]*h/2,z+b*cs-a*sn]}),pc=pack(col);for(const f of faces){const nx=f[6]*cs+f[8]*sn,ny=f[7],nz=f[8]*cs-f[6]*sn;for(let j=0;j<6;j++){const p=pts[f[j]];vertices[vi++]=p[0];vertices[vi++]=p[1];vertices[vi++]=p[2];vertices[vi++]=nx;vertices[vi++]=ny;vertices[vi++]=nz;vertices[vi++]=pc;vertices[vi++]=mat}}}
// Outfits are separate garment meshes (skins/boris-N.js) on Boris's shared head and hands; they load on demand.
const VER='1.7.0';const skins=[{name:'Дворовый классик',color:[.82,.80,.74],price:0,desc:'Рваная футболка, драные шорты, один ботинок с дыркой, второй просто грязный'},{name:'Король теплотрассы',color:[.34,.39,.23],price:120,desc:'Стёганый ватник, вязаная шапка, рюкзак с одеялом и бутылкой'},{name:'Бомжставка',color:[.98,.78,.10],price:250,desc:'Жёлтая куртка курьера, кепка и термокороб «Бомжставка» за спиной'},{name:'Abibas',color:[.09,.09,.11],price:450,desc:'Чёрный спортивный костюм с четырьмя полосами, кепка и золотая цепь'}];
const skinLoads={};function loadSkin(i){if(skinLoads[i]||(window.PIVNOY_SKINS&&window.PIVNOY_SKINS[i]))return;skinLoads[i]=true;const s=document.createElement('script');s.src=`skins/boris-${i}.js?v=${VER}`;s.onerror=()=>{skinLoads[i]=false;toast('Не удалось загрузить образ')};document.head.append(s);}
// Smooth, lit procedural meshes and articulated limbs. All geometry is original.
function vertex(p,n,c){vertices[vi++]=p[0];vertices[vi++]=p[1];vertices[vi++]=p[2];vertices[vi++]=n[0];vertices[vi++]=n[1];vertices[vi++]=n[2];vertices[vi++]=pack(c);vertices[vi++]=mat;}
const sphereMeshes=new Map(),litSphereMeshes=new Map();
function ellipsoid(x,y,z,rx,ry,rz,c,segs=12,rings=8){
 const key=segs+':'+rings;let mesh=sphereMeshes.get(key);
 if(!mesh){const points=[];const point=(i,j)=>{const a=i/rings*Math.PI,b=j/segs*Math.PI*2;return [Math.sin(a)*Math.cos(b),Math.cos(a),Math.sin(a)*Math.sin(b)];};for(let i=0;i<rings;i++)for(let j=0;j<segs;j++){const q=[point(i,j),point(i+1,j),point(i+1,j+1),point(i,j+1)];for(const k of [0,1,2,0,2,3])points.push(...q[k]);}mesh=new Float32Array(points);sphereMeshes.set(key,mesh);}
 const shapeKey=key+':'+rx+':'+ry+':'+rz;let shape=litSphereMeshes.get(shapeKey);
 if(!shape){shape=new Float32Array(mesh.length*2);for(let i=0,j=0;i<mesh.length;i+=3,j+=6){const nx=mesh[i]/rx,ny=mesh[i+1]/ry,nz=mesh[i+2]/rz,l=Math.hypot(nx,ny,nz);shape[j]=mesh[i]*rx;shape[j+1]=mesh[i+1]*ry;shape[j+2]=mesh[i+2]*rz;shape[j+3]=nx/l;shape[j+4]=ny/l;shape[j+5]=nz/l;}if(litSphereMeshes.size<500)litSphereMeshes.set(shapeKey,shape);}
 const pc=pack(c);for(let j=0;j<shape.length;j+=6){vertices[vi++]=x+shape[j];vertices[vi++]=y+shape[j+1];vertices[vi++]=z+shape[j+2];vertices[vi++]=shape[j+3];vertices[vi++]=shape[j+4];vertices[vi++]=shape[j+5];vertices[vi++]=pc;vertices[vi++]=mat;}
}
function limb(a,b,r1,r2,c,segments=8){const axis=b.map((v,i)=>v-a[i]),len=Math.hypot(...axis),n=axis.map(v=>v/len),u=Math.abs(n[1])>.95?[1,0,0]:[n[2],0,-n[0]],ul=Math.hypot(...u);for(let i=0;i<3;i++)u[i]/=ul;const v=[n[1]*u[2]-n[2]*u[1],n[2]*u[0]-n[0]*u[2],n[0]*u[1]-n[1]*u[0]];for(let i=0;i<segments;i++){const normals=[i,i+1].map(j=>u.map((k,t)=>k*Math.cos(j/segments*Math.PI*2)+v[t]*Math.sin(j/segments*Math.PI*2))),pts=[a.map((k,t)=>k+normals[0][t]*r1),b.map((k,t)=>k+normals[0][t]*r2),b.map((k,t)=>k+normals[1][t]*r2),a.map((k,t)=>k+normals[1][t]*r1)];for(const j of [0,1,2,0,2,3])vertex(pts[j],normals[j<2?0:1],c);}}
// Characters are sculpted mesh assets with a shared smooth skinning rig.
let actorRenderer=null;
function person(x,y,z,t,c,police=false,slide=false,pose={}){
 if(!actorRenderer)actorRenderer=new window.CharacterRenderer(gl);
 const kind=pose.rider?'rider':police?'police':'boris';
 actorRenderer.add(kind,x,y,z,t,c,Number(slide),pose);
}
function bottle(x,y,z,rot=0,s=1){const g=[.13,.47,.21],gd=[.09,.36,.16];mat=13;limb([x,y+.02*s,z],[x,y+.40*s,z],.09*s,.09*s,g,10);ellipsoid(x,y+.40*s,z,.09*s,.07*s,.09*s,g,10,4);limb([x,y+.44*s,z],[x,y+.60*s,z],.05*s,.034*s,gd,8);mat=6;limb([x,y+.60*s,z],[x,y+.655*s,z],.038*s,.038*s,[.80,.68,.30],8);ellipsoid(x,y+.655*s,z,.038*s,.006*s,.038*s,[.80,.68,.30],8,2);mat=0;limb([x,y+.13*s,z],[x,y+.31*s,z],.094*s,.094*s,[.92,.86,.66],10);limb([x,y+.20*s,z],[x,y+.24*s,z],.0955*s,.0955*s,[.72,.16,.14],10);mat=0;}
function car(x,z,variant=0){const c=[[.61,.18,.11],[.75,.68,.44],[.18,.34,.52],[.27,.38,.30]][variant%4];mat=6;box(x,.58,z,1.65,.6,3,c);box(x,1.02,z+.13,1.43,.55,1.48,c);mat=3;box(x,1.12,z-.63,1.22,.33,.035,colors.glass);box(x,1.12,z+.89,1.22,.31,.04,colors.glass);mat=6;box(x,.37,z-1.54,1.59,.12,.12,[.50,.53,.52]);mat=9;box(x,.61,z-1.53,.62,.22,.04,colors.dark);mat=6;box(x,.39,z-1.61,.41,.09,.015,[.91,.90,.80]);for(const side of [-1,1]){for(const dz of [-.95,1]){mat=9;ellipsoid(x+side*.81,.31,z+dz,.13,.31,.31,[.07,.085,.09],10,6);mat=6;ellipsoid(x+side*.935,.31,z+dz,.015,.16,.16,[.51,.54,.55],8,5);}for(const dz of [-.29,.43]){mat=3;box(x+side*.728,1.1,z+dz,.025,.30,.58,colors.glass);mat=6;box(x+side*.837,.72,z+dz,.026,.035,.18,[.72,.73,.69]);}mat=6;box(x+side*.86,1.0,z-.5,.25,.12,.18,c);mat=12;box(x+side*.56,.64,z-1.525,.38,.20,.035,[1,.89,.58]);box(x+side*.60,.65,z+1.52,.26,.17,.035,[.88,.15,.09]);}mat=6;box(x,.895,z-.95,1.45,.018,.75,c.map(v=>v*1.12));mat=0;}
function bench(x,z){mat=5;for(let i=0;i<4;i++){box(x,.60,z-.24+i*.16,1.65,.08,.12,colors.wood);box(x,.82+i*.13,z+.32,1.65,.09,.09,colors.wood);}mat=6;for(const side of [-1,1]){box(x+side*.64,.31,z,.07,.60,.43,colors.dark);box(x+side*.73,.8,z,.06,.36,.06,colors.dark);box(x+side*.73,.96,z,.07,.06,.63,colors.dark);}mat=0;}
// Pick-ups are recognisable objects, not cubes: a horseshoe magnet, a heater shield and a gold x2 coin, all spinning.
function spun(x,y,z,a){const c=Math.cos(a),s=Math.sin(a);return (dx,dy,dz)=>[x+dx*c+dz*s,y+dy,z-dx*s+dz*c];}
function magnetIcon(x,y,z,a){mat=6;const P=spun(x,y,z,a),red=[.82,.16,.12],tip=[.86,.88,.92];for(const side of [-1,1]){limb(P(side*.22,-.32,0),P(side*.22,.02,0),.075,.075,red,8);limb(P(side*.22,-.32,0),P(side*.22,-.19,0),.079,.079,tip,8);}let prev=P(-.22,.02,0);for(let i=1;i<=7;i++){const t=Math.PI*(1-i/7),q=P(Math.cos(t)*.22,.02+Math.sin(t)*.22,0);limb(prev,q,.075,.075,red,8);prev=q;}}
function shieldIcon(x,y,z,a){mat=6;const P=spun(x,y,z,a),B=(dx,dy,dz,w,h,d,col)=>{const p=P(dx,dy,dz);box(p[0],p[1],p[2],w,h,d,col,a)},steel=[.24,.50,.80],rim=[.10,.20,.38],gold=[.95,.78,.28];B(0,.12,-.005,.68,.36,.06,rim);B(0,-.12,-.005,.52,.22,.06,rim);B(0,-.27,-.005,.30,.16,.06,rim);B(0,.12,0,.62,.32,.09,steel);B(0,-.12,0,.46,.18,.09,steel);B(0,-.27,0,.24,.14,.09,steel);B(0,-.04,-.05,.08,.48,.02,gold);B(0,.10,-.05,.34,.08,.02,gold);}
const GLYPH_X=['1...1','.1.1.','..1..','.1.1.','1...1'],GLYPH_2=['11111','....1','....1','11111','1....','1....','11111'];
function coinIcon(x,y,z,a){mat=6;const P=spun(x,y,z,a),gold=[.96,.80,.30],edge=[.72,.55,.15],ink=[.32,.19,.05];limb(P(0,0,-.035),P(0,0,.035),.36,.36,edge,18);limb(P(0,0,-.036),P(0,0,-.035),0,.36,gold,18);limb(P(0,0,.035),P(0,0,.036),.36,0,gold,18);const cell=.052;for(const [glyph,ox] of [[GLYPH_X,-.30],[GLYPH_2,.03]]){const rows=glyph.length;glyph.forEach((row,r)=>{for(let c=0;c<row.length;c++)if(row[c]==='1'){const p=P(ox+c*cell,(rows/2-r-.5)*cell,-.046);box(p[0],p[1],p[2],cell,cell,.02,ink,a);}});}}
// Pigeons loiter on the asphalt in ones or flocks and scatter when the runner gets close.
function spawnPigeons(z){const n=Math.random()<.4?1:Math.random()<.65?2+rand(2):4+rand(4),birds=[];for(let i=0;i<n;i++)birds.push({x:(Math.random()-.5)*1.9,y:0,z:(Math.random()-.5)*1.9,vx:0,vy:0,vz:0,ph:Math.random()*6.28,face:Math.random()*6.28,tone:rand(4)});objects.push({type:'pigeons',lane:rand(3)-1,z,birds});}
function pigeons(o,dt){if(!o.fly&&o.z-distance<8.5+speed*.12){o.fly=true;sfx('flutter');for(const b of o.birds){const away=Math.sign(o.lane*2.15+b.x-px)||(Math.random()<.5?-1:1);b.vx=away*(1.2+Math.random()*2.2);b.vy=2.4+Math.random()*1.8;b.vz=1.5+Math.random()*2.5;b.face=Math.atan2(b.vx,b.vz);}}
 if(o.fly){for(const b of o.birds){b.x+=b.vx*dt;b.y+=b.vy*dt;b.z+=b.vz*dt;b.vy+=1.3*dt;b.vx*=1-.35*dt;}if(o.birds.every(b=>b.y>7))o.done=true;}}
function pigeon(x,y,z,face,flap,fly,ph,tone=0){const S=1.5,sx=Math.sin(face),cx=Math.cos(face),body=[[.46,.48,.55],[.30,.31,.36],[.72,.66,.60],[.52,.44,.40]][tone&3],dark=[[.28,.30,.38],[.18,.19,.24],[.60,.52,.46],[.36,.28,.26]][tone&3],neck=[.24,.50,.42],peck=fly?0:Math.max(0,Math.sin(time*5+ph))*.04*S;
 ellipsoid(x,y+.09*S,z,.095*S,.08*S,.115*S,body,8,5);ellipsoid(x+sx*.07*S,y+.135*S-peck*.5,z+cx*.07*S,.05*S,.042*S,.05*S,neck,6,4);ellipsoid(x+sx*.12*S,y+.165*S-peck,z+cx*.12*S,.046*S,.046*S,.046*S,dark,6,4);box(x+sx*.165*S,y+.16*S-peck,z+cx*.165*S,.02*S,.015*S,.035*S,[.85,.55,.25],face);
 box(x-sx*.15*S,y+.10*S,z-cx*.15*S,.06*S,.02*S,.12*S,dark,face);
 for(const s of [-1,1]){const px_=cx*s,pz_=-sx*s,reach=(fly?.26:.09)*S,tipY=y+.10*S+(fly?flap*.17:-.03)*S;limb([x+px_*.06*S,y+.12*S,z+pz_*.06*S],[x+px_*reach,tipY,z+pz_*reach],.045*S,.012*S,[.38,.40,.47],4);}
 if(!fly)for(const s of [-1,1])box(x+cx*s*.035*S,y+.02*S,z-sx*s*.035*S,.02*S,.04*S,.045*S,[.85,.45,.20],face);}
const CHASE_SECONDS=7,ROLL_DURATION=.76;let grounded=true,surfaceY=0,rollQueued=false;let slideBlend=0;let chase=0,chaseVisual=0,stumble=0,animTime=0,lean=0,landing=0,catchTime=0;
// Catch cinematic: Boris trips and slides, the world brakes, Semyonych runs in, whistles and hauls him up before the result sheet.
let caughtT=0,copZ=-8,copArrive=1,catchDecel=12,whistled=false;const lerp=(a,b,k)=>a+(b-a)*k,smooth=x=>{x=Math.max(0,Math.min(1,x));return x*x*(3-2*x)};
let mode='home',distance=0,speed=11,lane=0,px=0,jumpY=0,vy=0,slide=0,objects=[],nextRow=24,runBottles=0,shield=0,magnet=0,double=0,invincible=0,time=0,scenery=0,hitFlash=0,tab='upgrades',last=0,missionStart=0;
const rand=n=>Math.floor(Math.random()*n);function generateRow(z){const safe=rand(3)-1;const difficulty=Math.min(1,distance/700);for(let l=-1;l<=1;l++){if(l===safe){for(let k=0;k<4;k++)objects.push({type:'bottle',lane:l,z:z+k*1.6});if(Math.random()<.23)objects.push({type:['magnet','shield','double'][rand(3)],lane:l,z:z+8});}else if(Math.random()<.65+difficulty*.3){const type=['car','barrier','bar','scooter','debris'][rand(5)];objects.push({type,lane:l,z,variant:rand(4)});if(type==='car')objects.push({type:'bottle',lane:l,z:z+.12,y:1.295});}else{objects.push({type:'bottle',lane:l,z:z+2});}}if(Math.random()<.22)spawnPigeons(z+11+rand(5));}
function start(){scenery=0;grounded=true;surfaceY=0;rollQueued=false;slideBlend=0;chase=0;chaseVisual=0;stumble=0;catchTime=0;animTime=0;landing=0;lean=0;audioStart();distance=0;speed=11;lane=0;px=0;jumpY=0;vy=0;slide=0;objects=[];nextRow=24;runBottles=0;shield=save.shield>0?1:0;magnet=0;double=0;invincible=0;missionStart=save.total;mode='run';panel.innerHTML='';$('hud').hidden=false;$('controls').hidden=false;$('footer').hidden=true;save.runs++;persist();toast('Влево / вправо · вверх — прыжок · вниз — перекат');}
function carSurface(o,at){const rel=at-o.z;return rel>=-.64&&rel<=.90?1.295:.905;}
function supportAt(x,at){let h=0;for(const o of objects){if(o.type==='car'&&!o.done&&Math.abs(x-o.lane*2.15)<.79&&Math.abs(at-o.z)<1.50)h=Math.max(h,carSurface(o,at));}return h;}
function damage(kind){if(mode!=='run'||invincible>0)return;hitFlash=.30;sfx('hit');if(shield){shield=0;invincible=2+save.shield;toast('Ватник выдержал!');return;}if(kind==='fatal'||chase>0){startCatch();return;}chase=CHASE_SECONDS;stumble=.75;invincible=.65;toast('Семёныч рядом! Беги без ошибок');}
function startCatch(){mode='caught';caughtT=0;whistled=false;catchDecel=speed/.9;copZ=chaseVisual>.015?-6.5+chaseVisual*4.5:-8;copArrive=Math.max(.75,Math.min(1.4,(-1.05-copZ)/6));$('controls').hidden=true;persist();}
function caught(dt){caughtT+=dt;hitFlash=Math.max(0,hitFlash-dt);stumble=0;speed=Math.max(0,speed-dt*catchDecel);distance+=speed*dt;scenery+=speed*dt;
 if(jumpY>0){vy-=23*dt;jumpY=Math.max(0,jumpY+vy*dt);if(jumpY===0){vy=0;grounded=true;surfaceY=0;}}
 for(const o of objects)if(o.type==='scooter')o.z-=dt*2;objects=objects.filter(o=>!o.done&&!o.pull&&o.z>distance-8);
 $('meters').textContent=Math.floor(distance)+' м';
 if(!whistled&&caughtT>=copArrive){whistled=true;sfx('whistle');}
 if(caughtT>=copArrive+1.7)finish();}
function action(a){if(mode!=='run')return;
 if(a==='left'||a==='right'){const next=lane+(a==='left'?-1:1);if(Math.abs(next)>1){damage('stumble');return;}const obstacle=objects.find(o=>!o.done&&['car','barrier','bar','scooter'].includes(o.type)&&o.lane===next&&Math.abs(o.z-distance)<(o.type==='car'?1.95:.8));if(obstacle&&!(obstacle.type==='car'&&jumpY>=carSurface(obstacle,distance)-.04)&&!(obstacle.type==='barrier'&&jumpY>.95)&&!(obstacle.type==='bar'&&slide>0&&jumpY<.15)){damage('stumble');return;}lane=next;}
 if(a==='jump'&&grounded){vy=9.8;grounded=false;slide=0;slideBlend=0;rollQueued=false;sfx('jump');}
 if(a==='slide'){if(!grounded){vy=-13;rollQueued=true;}else if(slide<=0){slide=ROLL_DURATION;sfx('slide');}}}
// Semyonych never remembers what the charge is, so he invents one each time he catches up.
const CATCH_TITLES=['Ну что, добегался?','Гражданин, минутку!','Стоять, Гайкин!','Попался, голубчик','Так-так-так…'];
const CATCH_LINES=['Документы! Как это — нет? Тогда вы задержаны.','Гражданин Гайкин, вы обвиняетесь в незаконной сдаче стеклотары в особо крупном размере.','Наконец-то поймал! Зачем водку из магазина спёр?','Бег по проезжей части, прыжки по машинам, перекаты под перекладиной — это на три протокола.','Гражданин, минутку! Двадцать лет за вами бегаю — и вот.','Регистрация где? Теплотрасса — это не адрес, Борис.','Стой! Стрелять не буду — у меня только свисток.','Штраф за превышение скорости пешеходом. Сорок километров в час — это надо уметь.','Бутылки конфискуются как вещественное доказательство. Половина.','Пятнадцать суток. Или сдаёшь тару мне — по-соседски.'];
function finish(){const title=CATCH_TITLES[rand(CATCH_TITLES.length)],line=CATCH_LINES[rand(CATCH_LINES.length)];catchTime=0;chase=CHASE_SECONDS;mode='over';save.best=Math.max(save.best,Math.floor(distance));persist();$('controls').hidden=true;$('footer').hidden=false;panel.innerHTML=`<div class="sheet caught"><div class="eyebrow">СЕМЁНЫЧ ДОГНАЛ</div><h2>${title}</h2><p>«${line}»<br>Бутылки уже в кармане. Ещё по одной?</p><div class="stats"><div><strong>${Math.floor(distance)} м</strong><small>ДИСТАНЦИЯ</small></div><div><strong class="lime">+${runBottles}</strong><small>БУТЫЛОК</small></div></div><button class="primary" data-do="start">Ещё забег →</button><div class="row"><button class="secondary" data-do="shop">В приёмку</button><button class="secondary" data-do="home">Главная</button></div></div>`}
function pause(){if(mode==='run'){mode='pause';persist();panel.innerHTML='<div class="sheet"><div class="eyebrow">ПЕРЕКУР</div><h2>Улица подождёт</h2><p>Забег приостановлен.</p><button class="primary" data-do="resume">Продолжить →</button><div class="row"><button class="secondary" data-do="quit">Завершить забег</button></div></div>';}else if(mode==='pause')resume()}
function resume(){mode='run';panel.innerHTML='';audioStart()}
function home(){mode='home';$('hud').hidden=true;$('controls').hidden=true;$('footer').hidden=false;panel.innerHTML=`<div class="eyebrow">БЕСКОНЕЧНЫЕ УЛИЦЫ. БОЛЬШИЕ ПЛАНЫ.</div><h1>ПИВНОЙ<br><em>РЫВОК</em></h1><p>Весь район — твоя полоса препятствий.<br>Собирай бутылки. Не попадайся Семёнычу.</p><div class="stats"><div><strong>${save.best} м</strong><small>ЛИЧНЫЙ РЕКОРД</small></div><div><strong class="lime">${save.wallet}</strong><small>В КАРМАНЕ</small></div></div><button class="primary" data-do="start">Погнали! →</button><div class="row"><button class="secondary" data-do="shop">Приёмка</button><button class="secondary" data-do="story">История</button><button class="secondary" data-do="settings">⋯</button></div><div class="hint">Свайпы или стрелки / WASD · пробел — прыжок</div>`;if(!storageOK)toast('Сохранение недоступно — используйте экспорт')}
function shop(){mode='shop';$('hud').hidden=true;$('controls').hidden=true;let items='';if(tab==='upgrades'){for(const [k,name,desc]of [['magnet','Магнит из мастерской','Магнит действует на 3 секунды дольше за уровень.'],['shield','Крепкий ватник','Щит на старте; +1 сек. защиты после удара за уровень.'],['bonus','Вместительная сумка','Каждая бутылка: шанс 15% / 30% / 45% на дополнительную.']]){const lv=save[k],cost=(lv+1)*60;items+=`<div class="shop-item"><div class="info"><strong>${name} · ${lv}/3</strong><small>${desc}</small></div><button data-buy="${k}" ${lv===3||save.wallet<cost?'disabled':''}>${lv===3?'МАКС.':cost+' бут.'}</button></div>`}}else if(tab==='skins'){skins.forEach((s,i)=>{const owned=save.owned.includes(i);items+=`<div class="shop-item"><div class="swatch" style="background:rgb(${s.color.map(c=>c*255).join(',')})"></div><div class="info"><strong>${s.name}</strong><small>${s.desc}</small></div><button data-skin="${i}" ${save.skin===i||!owned&&save.wallet<s.price?'disabled':''}>${save.skin===i?'Надет':owned?'Надеть':s.price+' бут.'}</button></div>`})}else{[['Первая сотня',save.total,100,40],['Дорога домой',save.best,1000,100],['Постоянный клиент',save.runs,10,70]].forEach(([n,v,goal,reward],i)=>{items+=`<div class="shop-item"><div class="info"><strong>${n}</strong><small>${Math.min(v,goal)} / ${goal} ${i===0?'бутылок':i===1?'метров':'забегов'}</small></div><button data-claim="${i}" ${v<goal||save.claims.includes(i)?'disabled':''}>${save.claims.includes(i)?'Получено':'+'+reward}</button></div>`})}panel.innerHTML=`<div class="sheet"><div class="eyebrow">ПРИЁМ СТЕКЛОТАРЫ</div><h2>Приёмка у Тамары</h2><p>В кармане <b class="lime">${save.wallet} бутылок</b></p><div class="tabs">${[['upgrades','Улучшения'],['skins','Скины'],['missions','Задания']].map(([k,n])=>`<button data-tab="${k}" class="${tab===k?'active':''}">${n}</button>`).join('')}</div>${items}<button class="primary" data-do="start">На улицу →</button><div class="row"><button class="secondary" data-do="home">Назад</button></div></div>`}
function story(){mode='story';panel.innerHTML='<div class="sheet"><div class="eyebrow">ХРОНИКИ ЗАРЕЧЕНСКА · 01</div><h2>Борис и большое завтра</h2><p>Борис Гайкин когда-то чинил трамваи. Депо закрыли, общежитие продали — и он остался без дома. Теперь его адрес — теплотрасса у седьмого квартала, а мечта — своя маленькая мастерская.</p><p>Тамара из приёмки обещала придержать старый гараж. Плата простая: сдавай стеклотару, копи и не сдавайся. Борис объявил свой личный марафон.</p><p>Но участковый Семёныч увидел, как Борис перемахнул через ограду, и пустился следом. За что именно задерживать — он придумает по дороге.</p><p>Впереди панельные дворы, гаражи и проспект. Мешают машины, ремонтные барьеры и самокатчики. У каждого есть дела. У Бориса — большое завтра.</p><button class="primary" data-do="home">Понятно, погнали</button></div>'}
function settings(){mode='settings';panel.innerHTML=`<div class="sheet"><h2>Как играть</h2><p>← → / A D — сменить полосу<br>↑ / W / пробел — перепрыгнуть барьер<br>↓ / S — перекат под красной перекладиной<br>Esc / P — пауза. На машины можно запрыгивать, бежать по крыше и прыгать с неё. Самокатчиков обходите.</p><p>Лёгкая ошибка приближает Семёныча. Вторая за 7 секунд — поимка. Семь секунд чистого бега — отрыв. Удар в кузов машины, самокатчика или перекладину завершает забег. Приземление сверху на машину безопасно. Щит поглощает удар.</p><p>Зелёный бонус — магнит, голубой — щит, золотой — удвоение. На каждой группе препятствий остаётся свободная полоса.</p><p>Прогресс сохраняется в этом браузере. Для переноса в Telegram или на другое устройство экспортируйте сохранение, затем импортируйте файл там.</p><div class="row"><button class="secondary" data-do="export">Экспорт</button><button class="secondary" data-do="import">Импорт</button></div><p class="hint">iPhone: Safari → «Поделиться» → «На экран Домой». Звук включается после касания.</p><button class="primary" data-do="home">Назад</button></div>`}
panel.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;audioStart();const d=b.dataset;if(d.do){({start,home,shop,story,settings,resume,quit:finish,export:()=>{persist();const blob=new Blob([JSON.stringify(save,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='pivnoy-ryvok-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},import:()=>$('importFile').click()})[d.do]?.()}if(d.tab){tab=d.tab;shop()}if(d.buy){const k=d.buy,cost=(save[k]+1)*60;if(save[k]<3&&save.wallet>=cost){save.wallet-=cost;save[k]++;persist();sfx('collect');shop()}}if(d.skin!==undefined){const i=Number(d.skin);if(!save.owned.includes(i)&&save.wallet>=skins[i].price){save.wallet-=skins[i].price;save.owned.push(i)}if(save.owned.includes(i)){save.skin=i;loadSkin(i);}persist();shop()}if(d.claim!==undefined){const i=Number(d.claim),goals=[save.total>=100,save.best>=1000,save.runs>=10];if(goals[i]&&!save.claims.includes(i)){save.wallet+=[40,100,70][i];save.claims.push(i);persist();shop()}}});
$('importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>50000)throw Error();const next=validate(JSON.parse(await f.text()));if(confirm('Заменить текущий прогресс данными из файла?')){save=next;persist();home();toast('Прогресс восстановлен')}}catch(e){toast('Не удалось прочитать сохранение')}finally{$('importFile').value=''}};
$('pause').onclick=pause;document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();audioStart();action(b.dataset.action)}));
window.addEventListener('keydown',e=>{const key=e.key.toLowerCase(),map={arrowleft:'left',a:'left',arrowright:'right',d:'right',arrowup:'jump',w:'jump',' ':'jump',arrowdown:'slide',s:'slide'};if(map[key]){e.preventDefault();if(!e.repeat)action(map[key])}if(key==='escape'||key==='p')pause()});
let touch=null;canvas.addEventListener('pointerdown',e=>{touch={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);audioStart()});canvas.addEventListener('pointerup',e=>{if(!touch)return;const x=e.clientX-touch.x,y=e.clientY-touch.y;if(Math.max(Math.abs(x),Math.abs(y))>18)action(Math.abs(x)>Math.abs(y)?x>0?'right':'left':y>0?'slide':'jump');touch=null});canvas.addEventListener('pointercancel',()=>touch=null);document.addEventListener('visibilitychange',()=>{if(document.hidden){if(mode==='run')pause();if(ac)ac.suspend()}else if(ac&&save.sound)ac.resume()});window.addEventListener('pagehide',persist);
// Original composition “Seventh district”: 16-step bass, melody and synthesized percussion.
let ac=null,noteTime=0,step=0;const melody=[76,0,79,83,81,79,76,74,72,0,76,79,78,74,71,74,76,79,83,86,83,81,79,76,74,71,74,78,79,76,74,0],bass=[40,40,43,43,36,36,38,38];
function tone(freq,dur,type='triangle',vol=.04,at){if(!ac||!save.sound)return;const o=ac.createOscillator(),g=ac.createGain(),t=at??ac.currentTime;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(vol,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(ac.destination);o.start(t);o.stop(t+dur+.01)}
function audioStart(){if(!save.sound)return;try{if(!ac){ac=new(window.AudioContext||window.webkitAudioContext)();noteTime=ac.currentTime;step=0}if(ac.state==='suspended')ac.resume()}catch(e){}}
function music(){if(!ac||ac.state!=='running'||!save.sound)return;if(noteTime<ac.currentTime-.5)noteTime=ac.currentTime;while(noteTime<ac.currentTime+.12){const n=melody[step%32];if(n)tone(440*2**((n-69)/12),.17,'triangle',.022,noteTime);if(step%2===0)tone(440*2**((bass[Math.floor(step/4)%8]-69)/12),.23,'sine',.065,noteTime);if(step%4===0){tone(65,.12,'sine',.09,noteTime);tone(110,.035,'triangle',.025,noteTime)}if(step%2)tone(1700,.025,'square',.007,noteTime);step++;noteTime+=.155}}
function sfx(kind){if(kind==='collect'){tone(1000,.09,'sine',.06);tone(1500,.15,'sine',.035,ac?ac.currentTime+.06:undefined)}if(kind==='jump')tone(420,.14,'triangle',.04);if(kind==='slide')tone(150,.16,'sawtooth',.02);if(kind==='hit'){tone(75,.45,'sawtooth',.06);tone(92,.35,'square',.03)}if(kind==='whistle'){tone(2300,.30,'square',.022);tone(2650,.34,'square',.018,ac?ac.currentTime+.17:undefined)}if(kind==='flutter'){for(let i=0;i<6;i++)tone(650+Math.random()*450,.045,'triangle',.013,ac?ac.currentTime+i*.055:undefined)}if(kind==='power'){tone(660,.25);tone(990,.3,'triangle',.04,ac?ac.currentTime+.1:undefined)}}
$('sound').onclick=()=>{save.sound=!save.sound;$('sound').textContent=save.sound?'♪':'♪̸';if(save.sound)audioStart();else if(ac)ac.suspend();persist()};$('sound').textContent=save.sound?'♪':'♪̸';
function update(dt){if(mode==='caught'){caught(dt);return;}if(mode!=='run')return;animTime+=dt*speed*1.25;chase=Math.max(0,chase-dt);stumble=Math.max(0,stumble-dt);landing=Math.max(0,landing-dt);const targetLean=(lane*2.15-px)*.55;lean+=(targetLean-lean)*Math.min(1,dt*10);chaseVisual+=(Number(chase>0)-chaseVisual)*Math.min(1,dt*(chase>0?4:1.5));speed=Math.min(26,11+distance*.006)*(stumble>0?.78:1);distance+=speed*dt;scenery+=speed*dt;px+=(lane*2.15-px)*Math.min(1,dt*15);const oldY=jumpY;const support=supportAt(px,distance);surfaceY=support;
if(grounded&&Math.abs(jumpY-support)>.07)grounded=false;
if(!grounded||vy!==0){vy-=23*dt;jumpY+=vy*dt;if(vy<=0&&oldY>=support-.06&&jumpY<=support){jumpY=support;vy=0;grounded=true;landing=.18;if(rollQueued){rollQueued=false;slide=ROLL_DURATION;sfx('slide');}}}else jumpY=support;
if(jumpY<=0){jumpY=0;vy=0;grounded=true;}
slide=Math.max(0,slide-dt);slideBlend=slide>0?Math.min(1,(ROLL_DURATION-slide)/.085,slide/.085):0;magnet=Math.max(0,magnet-dt);double=Math.max(0,double-dt);invincible=Math.max(0,invincible-dt);hitFlash=Math.max(0,hitFlash-dt);
while(nextRow<distance+100){generateRow(nextRow);nextRow+=Math.max(20,speed*1.35)+rand(5)}
for(const o of objects){if(o.done)continue;if(o.type==='pigeons'){pigeons(o,dt);continue;}if(o.type==='scooter')o.z-=dt*2;const z=o.z-distance,dx=Math.abs(o.lane*2.15-px),collect=['shield','magnet','double'].includes(o.type);if(o.type==='bottle'){if(o.x===undefined){o.x=o.lane*2.15;o.h=(o.y||0)+.5;}if(!o.pull){if(magnet>0&&z<7&&z>-.6)o.pull=1;else if(Math.abs(z)<1.05&&dx<.85&&Math.abs(jumpY-(o.y||0))<1.25)o.pull=2;}if(o.pull){const ty=jumpY+1.05,tz=distance+.25,k=Math.min(1,dt*(o.pull===1?6+Math.max(0,7-z)*2.2:24));o.x+=(px-o.x)*k;o.h+=(ty-o.h)*k;o.z+=(tz-o.z)*k;if(Math.hypot(o.x-px,o.h-ty,o.z-tz)<.32){o.done=true;const val=(double>0?2:1)+(Math.random()<save.bonus*.15?1:0);runBottles+=val;save.wallet+=val;save.total++;persist();sfx('collect')}}continue;}if(collect){if(Math.abs(z)<1.05&&dx<.85&&Math.abs(jumpY-(o.y||0))<1.25){o.done=true;{if(o.type==='shield')shield=1;if(o.type==='magnet')magnet=7+save.magnet*3;if(o.type==='double')double=9;sfx('power');toast({shield:'Щит готов',magnet:'Магнит включён',double:'Бутылки ×2'}[o.type])}}}else if(Math.abs(z)<(o.type==='car'?1.5:.65)&&dx<.88){const safe=(o.type==='car'&&jumpY>=carSurface(o,distance)-.06)||(o.type==='barrier'&&jumpY>.95)||(o.type==='debris'&&jumpY>.30)||(o.type==='bar'&&slide>0&&jumpY<.15);if(!safe&&invincible<=0){o.done=true;damage(o.type==='debris'||o.type==='barrier'?'stumble':'fatal');if(mode==='over')break;}}}
objects=objects.filter(o=>!o.done&&o.z>distance-8);save.best=Math.max(save.best,Math.floor(distance));if(Math.floor(distance/25)!==Math.floor((distance-speed*dt)/25))persist();$('meters').textContent=Math.floor(distance)+' м';$('bottles').textContent=runBottles;$('powers').textContent=[chase>0?'⚠ СЕМЁНЫЧ РЯДОМ':'',shield?'◆ Щит':'',magnet>0?'МАГНИТ '+Math.ceil(magnet)+'с':'',double>0?'×2 '+Math.ceil(double)+'с':'',Math.floor(speed*3.6)+' км/ч'].filter(Boolean).join(' · ')}
const sceneryCache=new Map();
function scenerySegment(idx,z){let data=sceneryCache.get(idx);if(!data){const savedVertices=vertices,savedVi=vi;vertices=new Float32Array(240000);vi=0;const z=0;
for(const s of [-1,1]){const height=7+(((idx*7+(s+1)*2)%5+5)%5)*1.6,palette=((Math.floor(idx/8)%3)+3)%3,col=[[.65,.58,.45],[.59,.63,.58],[.62,.46,.34]][palette];mat=palette===2?10:2;box(s*9,height/2,z,5,height,13,col);mat=0;box(s*9,height+.16,z,5.3,.3,13.3,colors.dark);for(let floor=1;floor<height-1;floor+=2)for(let bz=-4;bz<=4;bz+=3){const lit=(idx+Math.floor(floor))%3===0;mat=lit?12:3;box(s*6.47,floor+.3,z+bz,.05,.9,1.1,lit?[.87,.80,.43]:[.28,.43,.47]);}mat=0;if(idx%2===0){mat=6;box(s*4.9,2.7,z,.11,5.4,.11,colors.dark);box(s*4.4,5.4,z,1.1,.13,.14,colors.dark);mat=12;box(s*3.95,5.32,z,.5,.08,.4,[1,.89,.52]);mat=0;bench(s*4.8,z+4)}else{mat=5;box(s*5.1,1.2,z,.23,2.4,.23,colors.wood);mat=4;ellipsoid(s*5.1,3.15,z,.88,1.42,.88,colors.green,9,5);ellipsoid(s*5.1+.4,3.7,z,.65,.92,.7,[.35,.61,.36],8,5);ellipsoid(s*5.1-.35,2.9,z+.3,.6,.8,.6,[.24,.48,.30],8,5);mat=0}if(idx%3===0)box(s*6.35,2,z-3,.15,.75,3,[.27,.49,.50]);if(true){for(let f=1;f<height-1;f+=2)for(let zz=-4;zz<=4;zz+=3){box(s*6.42,f+.3,z+zz,.055,.95,.045,[.79,.79,.70]);box(s*6.42,f+.3,z+zz,.055,.045,1.12,[.79,.79,.70]);box(s*6.38,f-.20,z+zz,.20,.08,1.24,[.72,.72,.66]);if((idx+Math.floor(f)+zz)%4===0){box(s*6.13,f-.17,z+zz,.62,.11,1.65,[.46,.48,.46]);box(s*5.83,f+.14,z+zz,.07,.64,1.65,col);}}box(s*6.42,1,z-1.2,.09,1.95,.92,[.18,.24,.24]);box(s*6.12,2.1,z-1.2,.65,.10,1.4,colors.dark);box(s*8,height+.45,z,1,.55,1,[.48,.46,.40]);mat=7;for(let q=-5;q<8;q+=2)box(s*4.8,.166,z+q,2.1,.012,.025,[.39,.43,.41]);mat=0;box(s*3.8,.18,z+6,.32,.018,.75,colors.dark);for(let q=0;q<5;q++)box(s*3.8,.195,z+5.7+q*.14,.33,.012,.025,[.60,.60,.51]);if(idx%2===0){ellipsoid(s*5.3,.52,z+5,.25,.45,.25,[.21,.31,.28],8,4);box(s*5.3,.97,z+5,.55,.06,.55,colors.dark);}}}
 data=vertices.slice(0,vi);vertices=savedVertices;vi=savedVi;sceneryCache.set(idx,data);}
 for(let i=0;i<data.length;i+=8){vertices[vi++]=data[i];vertices[vi++]=data[i+1];vertices[vi++]=data[i+2]+z;vertices[vi++]=data[i+3];vertices[vi++]=data[i+4];vertices[vi++]=data[i+5];vertices[vi++]=data[i+6];vertices[vi++]=data[i+7];}
}
function scenerySlots(at){const base=Math.floor(at/16);return Array.from({length:11},(_,n)=>({id:base+n-2,z:(base+n-2)*16-at+3}));}
// Sky: vertical strips of a horizon-to-zenith gradient on a far unlit quad (material 11).
function sky(){mat=11;const stops=[[0,[.74,.82,.88]],[6,[.66,.77,.87]],[16,[.52,.68,.85]],[34,[.40,.58,.82]],[70,[.30,.47,.76]]];for(let i=0;i<stops.length-1;i++){const [y0,c0]=stops[i],[y1,c1]=stops[i+1],p0=pack(c0),p1=pack(c1);for(const [x,y,pc] of [[-120,y0,p0],[120,y0,p0],[120,y1,p1],[-120,y0,p0],[120,y1,p1],[-120,y1,p1]]){vertices[vi++]=x;vertices[vi++]=y-1;vertices[vi++]=96;vertices[vi++]=0;vertices[vi++]=0;vertices[vi++]=-1;vertices[vi++]=pc;vertices[vi++]=11;}}mat=0;}
function draw(){bindEnv();const dpr=Math.min(devicePixelRatio||1,1.7),w=Math.floor(canvas.clientWidth*dpr),h=Math.floor(canvas.clientHeight*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h)}gl.uniform1f(aspect,w/h);gl.uniform1f(uScroll,distance);gl.uniform1f(uShadow,0);gl.clearColor(.68,.79,.87,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT|gl.STENCIL_BUFFER_BIT);vi=0;sky();mat=8;box(0,-.25,50,80,.3,135,[.31,.42,.34]);mat=1;box(0,-.07,52,7.2,.16,135,colors.road);mat=7;for(const side of [-1,1]){box(side*4.75,.02,52,2.25,.28,135,colors.walk);box(side*3.66,.13,52,.17,.22,135,[.79,.78,.64]);}mat=0;
const offset=scenery%8;for(let z=-6;z<110;z+=8){for(const x of [-1.075,1.075])box(x,.025,z-offset,.10,.025,3,[.83,.84,.66]);}
const slots=scenerySlots(scenery);for(const slot of slots)scenerySegment(slot.id,slot.z);for(const id of sceneryCache.keys())if(id<slots[0].id||id>slots[slots.length-1].id)sceneryCache.delete(id);
const propsStart=vi;if(mode==='run'||mode==='pause'||mode==='over'||mode==='caught'){for(const o of objects){const z=o.z-distance,x=o.lane*2.15;if(z< -5||z>100||o.done)continue;if(o.type==='bottle'){const bx=o.x!==undefined?o.x:x,by=o.h!==undefined?o.h:(o.y||0)+.5,bz=o.pull?o.z-distance:z,sc=o.pull?Math.max(.3,Math.min(1,Math.hypot(bx-px,by-(jumpY+1.05),bz-.25)/1.1)):1;bottle(bx,by+(o.pull?0:Math.sin(time*3+o.z)*.08),bz,time*(o.pull?10:1),sc);}else if(o.type==='car')car(x,z,o.variant);else if(o.type==='debris'){mat=10;for(let k=0;k<3;k++)box(x+(k-1)*.44,.12,z+(k%2)*.15,.43,.24,.42,[.52,.28,.18],k*.3);mat=0;}else if(o.type==='barrier'){mat=6;box(x,.53,z,1.65,1.06,.4,[.90,.39,.17]);for(const sx of [-.55,0,.55])box(x+sx,.63,z-.22,.23,.6,.025,[.96,.85,.62]);mat=0;}else if(o.type==='bar'){mat=6;for(const s of [-.8,.8])box(x+s,1.3,z,.14,2.6,.16,[.62,.24,.19]);box(x,1.97,z,1.75,.65,.3,[.78,.25,.15]);box(x,1.97,z-.16,1.6,.13,.02,[.97,.79,.51]);mat=0;}else if(o.type==='scooter'){mat=6;box(x,.18,z,.22,.17,1.2,colors.dark);box(x,.8,z-.47,.10,1.4,.1,[.84,.78,.3]);box(x,1.5,z-.47,.7,.08,.08,colors.dark);for(const zz of [-.5,.5]){mat=9;ellipsoid(x,.17,z+zz,.10,.17,.17,colors.dark,8,5);mat=6;ellipsoid(x-.105,.17,z+zz,.014,.085,.085,[.62,.64,.57],8,4);}mat=9;box(x,.28,z,.29,.025,.8,[.47,.48,.44]);for(const side of [-1,1])box(x+side*.28,1.5,z-.47,.17,.11,.11,[.14,.16,.15]);mat=0;person(x,.25,z+.14,time*2+z*.37,[.55,.24,.13],false,false,{rider:true,yaw:Math.PI});}else if(o.type==='pigeons'){for(const b of o.birds)pigeon(x+b.x,b.y,z+b.z,b.face,Math.sin(time*22+b.ph),o.fly,b.ph,b.tone);}else{const yy=1.1+Math.sin(time*4+o.z)*.12,rock=Math.sin(time*2.1+o.z)*.55;if(o.type==='shield')shieldIcon(x,yy,z,rock);else if(o.type==='magnet')magnetIcon(x,yy,z,time*1.9+o.z);else coinIcon(x,yy,z,rock);mat=0;}}}
else{bottle(-2.15,.3,9,time);bottle(-2.15,.3,12,time);bottle(0,.3,17,time);car(2.15,22,0);car(-2.15,49,2);pigeon(1.5,0,15.6,2.2,0,false,1,0);pigeon(2.4,0,16.5,3.1,0,false,2.5,2);pigeon(1.0,0,17.0,1.3,0,false,4.2,1);pigeon(2.7,0,15.1,.6,0,false,3.3,3);}const propsEnd=vi;
const running=mode==='run',live=running||mode==='pause',onStreet=live||mode==='over'||mode==='caught',py=onStreet?jumpY:0,pX=onStreet?px:0;
// Squash on touchdown, stretch along the jump arc; the roll deformation takes over while sliding.
const stretch=!running?0:slide>0?0:!grounded?Math.max(-.06,Math.min(.10,vy*.009)):-(landing/.18)*.09;
const pace=Math.max(0,Math.min(1,(speed-11)/15));
// Catch cinematic phases: trip and fall (0.45 s), slide face down, then get hauled up onto the knees once Semyonych arrives.
const fall=mode==='caught'?smooth(caughtT/.45):mode==='over'?1:0,rise=mode==='caught'?smooth((caughtT-copArrive-.15)/.6):mode==='over'?1:0;
if(!(invincible>0&&Math.floor(time*10)%2)){person(pX,py,0,live||mode==='caught'?animTime:time*2,skins[save.skin].color,false,live?Math.max(slideBlend,landing*.7):0,{skin:save.skin,roll:live&&slide>0?1-slide/ROLL_DURATION:0,air:grounded?0:Math.max(0,py-surfaceY),trip:live?stumble:0,lean:live?lean:0,vy:running?vy:0,stretch,speed:pace,fall,rise,idle:!['run','pause','caught'].includes(mode),arrest:mode==='over'?1:0});}
// Semyonych closes in behind, then steps up beside Boris and turns to face him so both stay in view.
if(chaseVisual>.015||mode==='over'||mode==='caught'){const arrived=mode==='over'||(mode==='caught'&&caughtT>=copArrive),k=mode==='over'?1:mode==='caught'?smooth(caughtT/copArrive):0,cz=mode==='caught'||mode==='over'?lerp(copZ,-.30,k):-6.5+chaseVisual*4.5,cx=lerp(pX*.9+.38,pX+.92,k),face=mode==='over'?1:mode==='caught'?smooth((caughtT-copArrive+.25)/.45):0;person(cx,0,cz,arrived?time*2:mode==='caught'?time*2.4:animTime*.97,[.13,.27,.43],true,false,{speed:mode==='caught'?.6:pace,yaw:-1.05*face,idle:arrived||!live&&mode!=='caught',arrest:arrived?1:0});}
if(stumble>0)for(let k=0;k<5;k++)ellipsoid(pX+Math.sin(k*9+time*5)*.48,.05+k*.04,-.4-k*.17,.10,.055,.09,[.60,.53,.39],6,3);

canvas.style.filter=hitFlash>0?'sepia(.4) saturate(1.6)':'none';
if(vi>vertices.length)throw Error('Geometry buffer overflow');
bindEnv();gl.bufferData(gl.ARRAY_BUFFER,vertices.subarray(0,vi),gl.DYNAMIC_DRAW);gl.drawArrays(gl.TRIANGLES,0,vi/8);
// Planar shadows: props and characters projected onto the road along the sun; the stencil keeps every shadow pixel single-layered.
gl.enable(gl.STENCIL_TEST);gl.stencilFunc(gl.EQUAL,0,0xff);gl.stencilOp(gl.KEEP,gl.KEEP,gl.INCR);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);
if(propsEnd>propsStart){gl.uniform1f(uShadow,1);gl.drawArrays(gl.TRIANGLES,propsStart/8,(propsEnd-propsStart)/8);gl.uniform1f(uShadow,0);}
gl.depthMask(true);gl.disable(gl.BLEND);gl.disable(gl.STENCIL_TEST);
if(actorRenderer)actorRenderer.draw(w/h,true);if(shield>0&&onStreet)dome(pX,py+1.0,0,.88,1.22,.88,w/h);}
function frame(ms){const dt=Math.min((ms-last)/1000||0,.035);last=ms;time+=dt;update(dt);draw();music();requestAnimationFrame(frame)}
loadSkin(save.skin);home();requestAnimationFrame(frame);
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
// Telegram SDK is optional; offline and browser gameplay never depend on it.
if(location.hash.includes('tgWebAppData')||location.search.includes('tgWebApp')){const script=document.createElement('script');script.src='https://telegram.org/js/telegram-web-app.js';script.onload=()=>{const tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand();if(tg.isVersionAtLeast('7.7'))tg.disableVerticalSwipes();tg.setHeaderColor('#152b36');tg.setBackgroundColor('#152b36');tg.BackButton.onClick(()=>{if(mode==='run')pause();else if(mode==='pause')resume();else home()});tg.BackButton.show()}};document.head.append(script)}
})();
